### PR TITLE
Test

### PR DESCRIPTION
**Pull request by DannyMcwaves**

### CODE REVIEW

**Comment by DannyMcwaves** [comment]
`PLEASE DO NOT MERGE THIS!!!`

@JoshuaVSherman the custom components components are not rendering at all. Those are google polymer elements?

**Comment by JoshuaVSherman** [comment]
Please remove all polymer components,  just use what we are currently using
fyi clcwebsite

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman tests are running successfully now. but apparently codeclimate has to be configured properly.

screen shot 2019-01-17 at 11 22 25 am

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please delete /static/includes.html

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman the requested changes have been made.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please fix so we don't get these compile warnings:

WARNING in ./src/app.js 30:0-33
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:7777 aurelia-bootstrapper

WARNING in ./src/app.js 31:0-29
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry (webpack)-dev-server/client?http://localhost:7777 aurelia-bootstrapper

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves the slideshow on home page is not correct, width is wrong on photos, please fix

image

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves looks like that column on every page is incorrect, the contact page also

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves missing the menu that changes for cellphone display, please fix or add from CLCwebsite project into this one, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I'm not done with all the fix just yet.
I just wanted to get the tests and structures up and running before making any UI changes.

I'll make the UI updates over the weekend.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves ok thank you, talk to you later :)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I made new changes yesterday. could you review it?

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves hey Danny, no there are still issues with the website, please just look here
https://www.appersonautomotive.com/

then look at the new one and you can easily see many issues, for example:
* slideshow is not same dimensions
* missing coupon graphic
* contact page text and graphic are off-page

please be sure to look at the page layout in widescreen, ipad size, and cellphone size to make sure it all fits on page and responds correctly.

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman

**Pull request merged**
